// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ovreplace
arma::mat ovreplace(arma::vec allst321, arma::vec idx321old, arma::vec idx321new, arma::vec convtype, arma::vec eststag3, arma::vec gvnrate, arma::vec multipl);
RcppExport SEXP _lefko3_ovreplace(SEXP allst321SEXP, SEXP idx321oldSEXP, SEXP idx321newSEXP, SEXP convtypeSEXP, SEXP eststag3SEXP, SEXP gvnrateSEXP, SEXP multiplSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type allst321(allst321SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type idx321old(idx321oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type idx321new(idx321newSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type convtype(convtypeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eststag3(eststag3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gvnrate(gvnrateSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type multipl(multiplSEXP);
    rcpp_result_gen = Rcpp::wrap(ovreplace(allst321, idx321old, idx321new, convtype, eststag3, gvnrate, multipl));
    return rcpp_result_gen;
END_RCPP
}
// pfj
Rcpp::List pfj(DataFrame data, DataFrame stageframe, int noyears, int firstyear, int popidcol, int patchidcol, int individcol, int blocksize, arma::ivec xcol, arma::ivec ycol, arma::ivec juvcol, arma::ivec sizeacol, arma::ivec sizebcol, arma::ivec sizeccol, arma::ivec repstracol, arma::ivec repstrbcol, arma::ivec fecacol, arma::ivec fecbcol, arma::ivec indcovacol, arma::ivec indcovbcol, arma::ivec indcovccol, arma::ivec aliveacol, arma::ivec deadacol, arma::ivec obsacol, arma::ivec nonobsacol, arma::ivec censorcol, arma::ivec stagecol, double repstrrel, double fecrel, bool NAas0, bool NRasRep, bool RepasObs, bool NOasObs, bool stassign, int stszcol, double censorkeep, bool censbool, bool censrepeat, bool coordsrepeat, bool quiet);
RcppExport SEXP _lefko3_pfj(SEXP dataSEXP, SEXP stageframeSEXP, SEXP noyearsSEXP, SEXP firstyearSEXP, SEXP popidcolSEXP, SEXP patchidcolSEXP, SEXP individcolSEXP, SEXP blocksizeSEXP, SEXP xcolSEXP, SEXP ycolSEXP, SEXP juvcolSEXP, SEXP sizeacolSEXP, SEXP sizebcolSEXP, SEXP sizeccolSEXP, SEXP repstracolSEXP, SEXP repstrbcolSEXP, SEXP fecacolSEXP, SEXP fecbcolSEXP, SEXP indcovacolSEXP, SEXP indcovbcolSEXP, SEXP indcovccolSEXP, SEXP aliveacolSEXP, SEXP deadacolSEXP, SEXP obsacolSEXP, SEXP nonobsacolSEXP, SEXP censorcolSEXP, SEXP stagecolSEXP, SEXP repstrrelSEXP, SEXP fecrelSEXP, SEXP NAas0SEXP, SEXP NRasRepSEXP, SEXP RepasObsSEXP, SEXP NOasObsSEXP, SEXP stassignSEXP, SEXP stszcolSEXP, SEXP censorkeepSEXP, SEXP censboolSEXP, SEXP censrepeatSEXP, SEXP coordsrepeatSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type stageframe(stageframeSEXP);
    Rcpp::traits::input_parameter< int >::type noyears(noyearsSEXP);
    Rcpp::traits::input_parameter< int >::type firstyear(firstyearSEXP);
    Rcpp::traits::input_parameter< int >::type popidcol(popidcolSEXP);
    Rcpp::traits::input_parameter< int >::type patchidcol(patchidcolSEXP);
    Rcpp::traits::input_parameter< int >::type individcol(individcolSEXP);
    Rcpp::traits::input_parameter< int >::type blocksize(blocksizeSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type xcol(xcolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ycol(ycolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type juvcol(juvcolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type sizeacol(sizeacolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type sizebcol(sizebcolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type sizeccol(sizeccolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type repstracol(repstracolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type repstrbcol(repstrbcolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type fecacol(fecacolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type fecbcol(fecbcolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type indcovacol(indcovacolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type indcovbcol(indcovbcolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type indcovccol(indcovccolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type aliveacol(aliveacolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type deadacol(deadacolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type obsacol(obsacolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type nonobsacol(nonobsacolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type censorcol(censorcolSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type stagecol(stagecolSEXP);
    Rcpp::traits::input_parameter< double >::type repstrrel(repstrrelSEXP);
    Rcpp::traits::input_parameter< double >::type fecrel(fecrelSEXP);
    Rcpp::traits::input_parameter< bool >::type NAas0(NAas0SEXP);
    Rcpp::traits::input_parameter< bool >::type NRasRep(NRasRepSEXP);
    Rcpp::traits::input_parameter< bool >::type RepasObs(RepasObsSEXP);
    Rcpp::traits::input_parameter< bool >::type NOasObs(NOasObsSEXP);
    Rcpp::traits::input_parameter< bool >::type stassign(stassignSEXP);
    Rcpp::traits::input_parameter< int >::type stszcol(stszcolSEXP);
    Rcpp::traits::input_parameter< double >::type censorkeep(censorkeepSEXP);
    Rcpp::traits::input_parameter< bool >::type censbool(censboolSEXP);
    Rcpp::traits::input_parameter< bool >::type censrepeat(censrepeatSEXP);
    Rcpp::traits::input_parameter< bool >::type coordsrepeat(coordsrepeatSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(pfj(data, stageframe, noyears, firstyear, popidcol, patchidcol, individcol, blocksize, xcol, ycol, juvcol, sizeacol, sizebcol, sizeccol, repstracol, repstrbcol, fecacol, fecbcol, indcovacol, indcovbcol, indcovccol, aliveacol, deadacol, obsacol, nonobsacol, censorcol, stagecol, repstrrel, fecrel, NAas0, NRasRep, RepasObs, NOasObs, stassign, stszcol, censorkeep, censbool, censrepeat, coordsrepeat, quiet));
    return rcpp_result_gen;
END_RCPP
}
// jpf
Rcpp::List jpf(DataFrame data, DataFrame stageframe, int popidcol, int patchidcol, int individcol, int year2col, int year3col, int xcol, int ycol, int juv2col, int juv3col, int sizea2col, int sizea3col, int sizeb2col, int sizeb3col, int sizec2col, int sizec3col, int repstra2col, int repstra3col, int repstrb2col, int repstrb3col, int feca2col, int feca3col, int fecb2col, int fecb3col, int indcova2col, int indcova3col, int indcovb2col, int indcovb3col, int indcovc2col, int indcovc3col, int alive2col, int alive3col, int dead2col, int dead3col, int obs2col, int obs3col, int nonobs2col, int nonobs3col, double repstrrel, double fecrel, int stage2col, int stage3col, int censorcol, bool NAas0, bool NRasRep, bool NOasObs, bool stassign, int stszcol, double censorkeep, bool censbool, bool quiet);
RcppExport SEXP _lefko3_jpf(SEXP dataSEXP, SEXP stageframeSEXP, SEXP popidcolSEXP, SEXP patchidcolSEXP, SEXP individcolSEXP, SEXP year2colSEXP, SEXP year3colSEXP, SEXP xcolSEXP, SEXP ycolSEXP, SEXP juv2colSEXP, SEXP juv3colSEXP, SEXP sizea2colSEXP, SEXP sizea3colSEXP, SEXP sizeb2colSEXP, SEXP sizeb3colSEXP, SEXP sizec2colSEXP, SEXP sizec3colSEXP, SEXP repstra2colSEXP, SEXP repstra3colSEXP, SEXP repstrb2colSEXP, SEXP repstrb3colSEXP, SEXP feca2colSEXP, SEXP feca3colSEXP, SEXP fecb2colSEXP, SEXP fecb3colSEXP, SEXP indcova2colSEXP, SEXP indcova3colSEXP, SEXP indcovb2colSEXP, SEXP indcovb3colSEXP, SEXP indcovc2colSEXP, SEXP indcovc3colSEXP, SEXP alive2colSEXP, SEXP alive3colSEXP, SEXP dead2colSEXP, SEXP dead3colSEXP, SEXP obs2colSEXP, SEXP obs3colSEXP, SEXP nonobs2colSEXP, SEXP nonobs3colSEXP, SEXP repstrrelSEXP, SEXP fecrelSEXP, SEXP stage2colSEXP, SEXP stage3colSEXP, SEXP censorcolSEXP, SEXP NAas0SEXP, SEXP NRasRepSEXP, SEXP NOasObsSEXP, SEXP stassignSEXP, SEXP stszcolSEXP, SEXP censorkeepSEXP, SEXP censboolSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type stageframe(stageframeSEXP);
    Rcpp::traits::input_parameter< int >::type popidcol(popidcolSEXP);
    Rcpp::traits::input_parameter< int >::type patchidcol(patchidcolSEXP);
    Rcpp::traits::input_parameter< int >::type individcol(individcolSEXP);
    Rcpp::traits::input_parameter< int >::type year2col(year2colSEXP);
    Rcpp::traits::input_parameter< int >::type year3col(year3colSEXP);
    Rcpp::traits::input_parameter< int >::type xcol(xcolSEXP);
    Rcpp::traits::input_parameter< int >::type ycol(ycolSEXP);
    Rcpp::traits::input_parameter< int >::type juv2col(juv2colSEXP);
    Rcpp::traits::input_parameter< int >::type juv3col(juv3colSEXP);
    Rcpp::traits::input_parameter< int >::type sizea2col(sizea2colSEXP);
    Rcpp::traits::input_parameter< int >::type sizea3col(sizea3colSEXP);
    Rcpp::traits::input_parameter< int >::type sizeb2col(sizeb2colSEXP);
    Rcpp::traits::input_parameter< int >::type sizeb3col(sizeb3colSEXP);
    Rcpp::traits::input_parameter< int >::type sizec2col(sizec2colSEXP);
    Rcpp::traits::input_parameter< int >::type sizec3col(sizec3colSEXP);
    Rcpp::traits::input_parameter< int >::type repstra2col(repstra2colSEXP);
    Rcpp::traits::input_parameter< int >::type repstra3col(repstra3colSEXP);
    Rcpp::traits::input_parameter< int >::type repstrb2col(repstrb2colSEXP);
    Rcpp::traits::input_parameter< int >::type repstrb3col(repstrb3colSEXP);
    Rcpp::traits::input_parameter< int >::type feca2col(feca2colSEXP);
    Rcpp::traits::input_parameter< int >::type feca3col(feca3colSEXP);
    Rcpp::traits::input_parameter< int >::type fecb2col(fecb2colSEXP);
    Rcpp::traits::input_parameter< int >::type fecb3col(fecb3colSEXP);
    Rcpp::traits::input_parameter< int >::type indcova2col(indcova2colSEXP);
    Rcpp::traits::input_parameter< int >::type indcova3col(indcova3colSEXP);
    Rcpp::traits::input_parameter< int >::type indcovb2col(indcovb2colSEXP);
    Rcpp::traits::input_parameter< int >::type indcovb3col(indcovb3colSEXP);
    Rcpp::traits::input_parameter< int >::type indcovc2col(indcovc2colSEXP);
    Rcpp::traits::input_parameter< int >::type indcovc3col(indcovc3colSEXP);
    Rcpp::traits::input_parameter< int >::type alive2col(alive2colSEXP);
    Rcpp::traits::input_parameter< int >::type alive3col(alive3colSEXP);
    Rcpp::traits::input_parameter< int >::type dead2col(dead2colSEXP);
    Rcpp::traits::input_parameter< int >::type dead3col(dead3colSEXP);
    Rcpp::traits::input_parameter< int >::type obs2col(obs2colSEXP);
    Rcpp::traits::input_parameter< int >::type obs3col(obs3colSEXP);
    Rcpp::traits::input_parameter< int >::type nonobs2col(nonobs2colSEXP);
    Rcpp::traits::input_parameter< int >::type nonobs3col(nonobs3colSEXP);
    Rcpp::traits::input_parameter< double >::type repstrrel(repstrrelSEXP);
    Rcpp::traits::input_parameter< double >::type fecrel(fecrelSEXP);
    Rcpp::traits::input_parameter< int >::type stage2col(stage2colSEXP);
    Rcpp::traits::input_parameter< int >::type stage3col(stage3colSEXP);
    Rcpp::traits::input_parameter< int >::type censorcol(censorcolSEXP);
    Rcpp::traits::input_parameter< bool >::type NAas0(NAas0SEXP);
    Rcpp::traits::input_parameter< bool >::type NRasRep(NRasRepSEXP);
    Rcpp::traits::input_parameter< bool >::type NOasObs(NOasObsSEXP);
    Rcpp::traits::input_parameter< bool >::type stassign(stassignSEXP);
    Rcpp::traits::input_parameter< int >::type stszcol(stszcolSEXP);
    Rcpp::traits::input_parameter< double >::type censorkeep(censorkeepSEXP);
    Rcpp::traits::input_parameter< bool >::type censbool(censboolSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(jpf(data, stageframe, popidcol, patchidcol, individcol, year2col, year3col, xcol, ycol, juv2col, juv3col, sizea2col, sizea3col, sizeb2col, sizeb3col, sizec2col, sizec3col, repstra2col, repstra3col, repstrb2col, repstrb3col, feca2col, feca3col, fecb2col, fecb3col, indcova2col, indcova3col, indcovb2col, indcovb3col, indcovc2col, indcovc3col, alive2col, alive3col, dead2col, dead3col, obs2col, obs3col, nonobs2col, nonobs3col, repstrrel, fecrel, stage2col, stage3col, censorcol, NAas0, NRasRep, NOasObs, stassign, stszcol, censorkeep, censbool, quiet));
    return rcpp_result_gen;
END_RCPP
}
// theoldpizzle
Rcpp::List theoldpizzle(DataFrame StageFrame, DataFrame OverWrite, arma::mat repmatrix, int finalage, int format, int style, int cont);
RcppExport SEXP _lefko3_theoldpizzle(SEXP StageFrameSEXP, SEXP OverWriteSEXP, SEXP repmatrixSEXP, SEXP finalageSEXP, SEXP formatSEXP, SEXP styleSEXP, SEXP contSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type StageFrame(StageFrameSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type OverWrite(OverWriteSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type repmatrix(repmatrixSEXP);
    Rcpp::traits::input_parameter< int >::type finalage(finalageSEXP);
    Rcpp::traits::input_parameter< int >::type format(formatSEXP);
    Rcpp::traits::input_parameter< int >::type style(styleSEXP);
    Rcpp::traits::input_parameter< int >::type cont(contSEXP);
    rcpp_result_gen = Rcpp::wrap(theoldpizzle(StageFrame, OverWrite, repmatrix, finalage, format, style, cont));
    return rcpp_result_gen;
END_RCPP
}
// density3
Rcpp::NumericVector density3(Rcpp::DataFrame data, int xcol, int ycol, int yearcol, double spacing);
RcppExport SEXP _lefko3_density3(SEXP dataSEXP, SEXP xcolSEXP, SEXP ycolSEXP, SEXP yearcolSEXP, SEXP spacingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type xcol(xcolSEXP);
    Rcpp::traits::input_parameter< int >::type ycol(ycolSEXP);
    Rcpp::traits::input_parameter< int >::type yearcol(yearcolSEXP);
    Rcpp::traits::input_parameter< double >::type spacing(spacingSEXP);
    rcpp_result_gen = Rcpp::wrap(density3(data, xcol, ycol, yearcol, spacing));
    return rcpp_result_gen;
END_RCPP
}
// hoffmannofstuttgart
List hoffmannofstuttgart(arma::mat mainmat, DataFrame indices, int ahstages, StringVector stagenames);
RcppExport SEXP _lefko3_hoffmannofstuttgart(SEXP mainmatSEXP, SEXP indicesSEXP, SEXP ahstagesSEXP, SEXP stagenamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mainmat(mainmatSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< int >::type ahstages(ahstagesSEXP);
    Rcpp::traits::input_parameter< StringVector >::type stagenames(stagenamesSEXP);
    rcpp_result_gen = Rcpp::wrap(hoffmannofstuttgart(mainmat, indices, ahstages, stagenames));
    return rcpp_result_gen;
END_RCPP
}
// cond_hmpm
Rcpp::List cond_hmpm(List hmpm, Nullable<CharacterVector> matchoice, Nullable<LogicalVector> err_check);
RcppExport SEXP _lefko3_cond_hmpm(SEXP hmpmSEXP, SEXP matchoiceSEXP, SEXP err_checkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type hmpm(hmpmSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type matchoice(matchoiceSEXP);
    Rcpp::traits::input_parameter< Nullable<LogicalVector> >::type err_check(err_checkSEXP);
    rcpp_result_gen = Rcpp::wrap(cond_hmpm(hmpm, matchoice, err_check));
    return rcpp_result_gen;
END_RCPP
}
// specialpatrolgroup
List specialpatrolgroup(DataFrame sge9l, DataFrame sge3, DataFrame MainData, DataFrame StageFrame, int format, int err_switch);
RcppExport SEXP _lefko3_specialpatrolgroup(SEXP sge9lSEXP, SEXP sge3SEXP, SEXP MainDataSEXP, SEXP StageFrameSEXP, SEXP formatSEXP, SEXP err_switchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type sge9l(sge9lSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type sge3(sge3SEXP);
    Rcpp::traits::input_parameter< DataFrame >::type MainData(MainDataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type StageFrame(StageFrameSEXP);
    Rcpp::traits::input_parameter< int >::type format(formatSEXP);
    Rcpp::traits::input_parameter< int >::type err_switch(err_switchSEXP);
    rcpp_result_gen = Rcpp::wrap(specialpatrolgroup(sge9l, sge3, MainData, StageFrame, format, err_switch));
    return rcpp_result_gen;
END_RCPP
}
// normalpatrolgroup
List normalpatrolgroup(DataFrame sge3, DataFrame sge2, DataFrame MainData, DataFrame StageFrame);
RcppExport SEXP _lefko3_normalpatrolgroup(SEXP sge3SEXP, SEXP sge2SEXP, SEXP MainDataSEXP, SEXP StageFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type sge3(sge3SEXP);
    Rcpp::traits::input_parameter< DataFrame >::type sge2(sge2SEXP);
    Rcpp::traits::input_parameter< DataFrame >::type MainData(MainDataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type StageFrame(StageFrameSEXP);
    rcpp_result_gen = Rcpp::wrap(normalpatrolgroup(sge3, sge2, MainData, StageFrame));
    return rcpp_result_gen;
END_RCPP
}
// revelations
arma::mat revelations(List survproxy, List obsproxy, List sizeproxy, List sizebproxy, List sizecproxy, List repstproxy, List fecproxy, List jsurvproxy, List jobsproxy, List jsizeproxy, List jsizebproxy, List jsizecproxy, List jrepstproxy, int mat_switch);
RcppExport SEXP _lefko3_revelations(SEXP survproxySEXP, SEXP obsproxySEXP, SEXP sizeproxySEXP, SEXP sizebproxySEXP, SEXP sizecproxySEXP, SEXP repstproxySEXP, SEXP fecproxySEXP, SEXP jsurvproxySEXP, SEXP jobsproxySEXP, SEXP jsizeproxySEXP, SEXP jsizebproxySEXP, SEXP jsizecproxySEXP, SEXP jrepstproxySEXP, SEXP mat_switchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type survproxy(survproxySEXP);
    Rcpp::traits::input_parameter< List >::type obsproxy(obsproxySEXP);
    Rcpp::traits::input_parameter< List >::type sizeproxy(sizeproxySEXP);
    Rcpp::traits::input_parameter< List >::type sizebproxy(sizebproxySEXP);
    Rcpp::traits::input_parameter< List >::type sizecproxy(sizecproxySEXP);
    Rcpp::traits::input_parameter< List >::type repstproxy(repstproxySEXP);
    Rcpp::traits::input_parameter< List >::type fecproxy(fecproxySEXP);
    Rcpp::traits::input_parameter< List >::type jsurvproxy(jsurvproxySEXP);
    Rcpp::traits::input_parameter< List >::type jobsproxy(jobsproxySEXP);
    Rcpp::traits::input_parameter< List >::type jsizeproxy(jsizeproxySEXP);
    Rcpp::traits::input_parameter< List >::type jsizebproxy(jsizebproxySEXP);
    Rcpp::traits::input_parameter< List >::type jsizecproxy(jsizecproxySEXP);
    Rcpp::traits::input_parameter< List >::type jrepstproxy(jrepstproxySEXP);
    Rcpp::traits::input_parameter< int >::type mat_switch(mat_switchSEXP);
    rcpp_result_gen = Rcpp::wrap(revelations(survproxy, obsproxy, sizeproxy, sizebproxy, sizecproxy, repstproxy, fecproxy, jsurvproxy, jobsproxy, jsizeproxy, jsizebproxy, jsizecproxy, jrepstproxy, mat_switch));
    return rcpp_result_gen;
END_RCPP
}
// rimeotam
double rimeotam(arma::vec maincoefs, double fl1_i, double fl2n_i, double sz1_i, double sz2o_i, double szb1_i, double szb2o_i, double szc1_i, double szc2o_i, double aage2_i, double inda_1, double inda_2, double indb_1, double indb_2, double indc_1, double indc_2, double used_dens, bool zi);
RcppExport SEXP _lefko3_rimeotam(SEXP maincoefsSEXP, SEXP fl1_iSEXP, SEXP fl2n_iSEXP, SEXP sz1_iSEXP, SEXP sz2o_iSEXP, SEXP szb1_iSEXP, SEXP szb2o_iSEXP, SEXP szc1_iSEXP, SEXP szc2o_iSEXP, SEXP aage2_iSEXP, SEXP inda_1SEXP, SEXP inda_2SEXP, SEXP indb_1SEXP, SEXP indb_2SEXP, SEXP indc_1SEXP, SEXP indc_2SEXP, SEXP used_densSEXP, SEXP ziSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type maincoefs(maincoefsSEXP);
    Rcpp::traits::input_parameter< double >::type fl1_i(fl1_iSEXP);
    Rcpp::traits::input_parameter< double >::type fl2n_i(fl2n_iSEXP);
    Rcpp::traits::input_parameter< double >::type sz1_i(sz1_iSEXP);
    Rcpp::traits::input_parameter< double >::type sz2o_i(sz2o_iSEXP);
    Rcpp::traits::input_parameter< double >::type szb1_i(szb1_iSEXP);
    Rcpp::traits::input_parameter< double >::type szb2o_i(szb2o_iSEXP);
    Rcpp::traits::input_parameter< double >::type szc1_i(szc1_iSEXP);
    Rcpp::traits::input_parameter< double >::type szc2o_i(szc2o_iSEXP);
    Rcpp::traits::input_parameter< double >::type aage2_i(aage2_iSEXP);
    Rcpp::traits::input_parameter< double >::type inda_1(inda_1SEXP);
    Rcpp::traits::input_parameter< double >::type inda_2(inda_2SEXP);
    Rcpp::traits::input_parameter< double >::type indb_1(indb_1SEXP);
    Rcpp::traits::input_parameter< double >::type indb_2(indb_2SEXP);
    Rcpp::traits::input_parameter< double >::type indc_1(indc_1SEXP);
    Rcpp::traits::input_parameter< double >::type indc_2(indc_2SEXP);
    Rcpp::traits::input_parameter< double >::type used_dens(used_densSEXP);
    Rcpp::traits::input_parameter< bool >::type zi(ziSEXP);
    rcpp_result_gen = Rcpp::wrap(rimeotam(maincoefs, fl1_i, fl2n_i, sz1_i, sz2o_i, szb1_i, szb2o_i, szc1_i, szc2o_i, aage2_i, inda_1, inda_2, indb_1, indb_2, indc_1, indc_2, used_dens, zi));
    return rcpp_result_gen;
END_RCPP
}
// foi_counter
arma::ivec foi_counter(List modelproxy, bool zi);
RcppExport SEXP _lefko3_foi_counter(SEXP modelproxySEXP, SEXP ziSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type modelproxy(modelproxySEXP);
    Rcpp::traits::input_parameter< bool >::type zi(ziSEXP);
    rcpp_result_gen = Rcpp::wrap(foi_counter(modelproxy, zi));
    return rcpp_result_gen;
END_RCPP
}
// flightoficarus
arma::vec flightoficarus(List modelproxy);
RcppExport SEXP _lefko3_flightoficarus(SEXP modelproxySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type modelproxy(modelproxySEXP);
    rcpp_result_gen = Rcpp::wrap(flightoficarus(modelproxy));
    return rcpp_result_gen;
END_RCPP
}
// bootson
StringVector bootson(List modelproxy);
RcppExport SEXP _lefko3_bootson(SEXP modelproxySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type modelproxy(modelproxySEXP);
    rcpp_result_gen = Rcpp::wrap(bootson(modelproxy));
    return rcpp_result_gen;
END_RCPP
}
// zero_flightoficarus
arma::vec zero_flightoficarus(List modelproxy);
RcppExport SEXP _lefko3_zero_flightoficarus(SEXP modelproxySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type modelproxy(modelproxySEXP);
    rcpp_result_gen = Rcpp::wrap(zero_flightoficarus(modelproxy));
    return rcpp_result_gen;
END_RCPP
}
// zero_bootson
StringVector zero_bootson(List modelproxy);
RcppExport SEXP _lefko3_zero_bootson(SEXP modelproxySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type modelproxy(modelproxySEXP);
    rcpp_result_gen = Rcpp::wrap(zero_bootson(modelproxy));
    return rcpp_result_gen;
END_RCPP
}
// foi_index
arma::imat foi_index(List surv_proxy, List obs_proxy, List size_proxy, List sizeb_proxy, List sizec_proxy, List repst_proxy, List fec_proxy, List jsurv_proxy, List jobs_proxy, List jsize_proxy, List jsizeb_proxy, List jsizec_proxy, List jrepst_proxy);
RcppExport SEXP _lefko3_foi_index(SEXP surv_proxySEXP, SEXP obs_proxySEXP, SEXP size_proxySEXP, SEXP sizeb_proxySEXP, SEXP sizec_proxySEXP, SEXP repst_proxySEXP, SEXP fec_proxySEXP, SEXP jsurv_proxySEXP, SEXP jobs_proxySEXP, SEXP jsize_proxySEXP, SEXP jsizeb_proxySEXP, SEXP jsizec_proxySEXP, SEXP jrepst_proxySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type surv_proxy(surv_proxySEXP);
    Rcpp::traits::input_parameter< List >::type obs_proxy(obs_proxySEXP);
    Rcpp::traits::input_parameter< List >::type size_proxy(size_proxySEXP);
    Rcpp::traits::input_parameter< List >::type sizeb_proxy(sizeb_proxySEXP);
    Rcpp::traits::input_parameter< List >::type sizec_proxy(sizec_proxySEXP);
    Rcpp::traits::input_parameter< List >::type repst_proxy(repst_proxySEXP);
    Rcpp::traits::input_parameter< List >::type fec_proxy(fec_proxySEXP);
    Rcpp::traits::input_parameter< List >::type jsurv_proxy(jsurv_proxySEXP);
    Rcpp::traits::input_parameter< List >::type jobs_proxy(jobs_proxySEXP);
    Rcpp::traits::input_parameter< List >::type jsize_proxy(jsize_proxySEXP);
    Rcpp::traits::input_parameter< List >::type jsizeb_proxy(jsizeb_proxySEXP);
    Rcpp::traits::input_parameter< List >::type jsizec_proxy(jsizec_proxySEXP);
    Rcpp::traits::input_parameter< List >::type jrepst_proxy(jrepst_proxySEXP);
    rcpp_result_gen = Rcpp::wrap(foi_index(surv_proxy, obs_proxy, size_proxy, sizeb_proxy, sizec_proxy, repst_proxy, fec_proxy, jsurv_proxy, jobs_proxy, jsize_proxy, jsizeb_proxy, jsizec_proxy, jrepst_proxy));
    return rcpp_result_gen;
END_RCPP
}
// jerzeibalowski
List jerzeibalowski(DataFrame ppy, DataFrame AllStages, DataFrame stageframe, int matrixformat, List survproxy, List obsproxy, List sizeproxy, List sizebproxy, List sizecproxy, List repstproxy, List fecproxy, List jsurvproxy, List jobsproxy, List jsizeproxy, List jsizebproxy, List jsizecproxy, List jrepstproxy, NumericVector f2_inda, NumericVector f1_inda, NumericVector f2_indb, NumericVector f1_indb, NumericVector f2_indc, NumericVector f1_indc, StringVector r2_inda, StringVector r1_inda, StringVector r2_indb, StringVector r1_indb, StringVector r2_indc, StringVector r1_indc, NumericVector dev_terms, double dens, double fecmod, NumericVector svsigmas, double maxsize, double maxsizeb, double maxsizec, unsigned int finalage, int sizedist, int sizebdist, int sizecdist, int fecdist, bool negfec, double exp_tol, double theta_tol);
RcppExport SEXP _lefko3_jerzeibalowski(SEXP ppySEXP, SEXP AllStagesSEXP, SEXP stageframeSEXP, SEXP matrixformatSEXP, SEXP survproxySEXP, SEXP obsproxySEXP, SEXP sizeproxySEXP, SEXP sizebproxySEXP, SEXP sizecproxySEXP, SEXP repstproxySEXP, SEXP fecproxySEXP, SEXP jsurvproxySEXP, SEXP jobsproxySEXP, SEXP jsizeproxySEXP, SEXP jsizebproxySEXP, SEXP jsizecproxySEXP, SEXP jrepstproxySEXP, SEXP f2_indaSEXP, SEXP f1_indaSEXP, SEXP f2_indbSEXP, SEXP f1_indbSEXP, SEXP f2_indcSEXP, SEXP f1_indcSEXP, SEXP r2_indaSEXP, SEXP r1_indaSEXP, SEXP r2_indbSEXP, SEXP r1_indbSEXP, SEXP r2_indcSEXP, SEXP r1_indcSEXP, SEXP dev_termsSEXP, SEXP densSEXP, SEXP fecmodSEXP, SEXP svsigmasSEXP, SEXP maxsizeSEXP, SEXP maxsizebSEXP, SEXP maxsizecSEXP, SEXP finalageSEXP, SEXP sizedistSEXP, SEXP sizebdistSEXP, SEXP sizecdistSEXP, SEXP fecdistSEXP, SEXP negfecSEXP, SEXP exp_tolSEXP, SEXP theta_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type ppy(ppySEXP);
    Rcpp::traits::input_parameter< DataFrame >::type AllStages(AllStagesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type stageframe(stageframeSEXP);
    Rcpp::traits::input_parameter< int >::type matrixformat(matrixformatSEXP);
    Rcpp::traits::input_parameter< List >::type survproxy(survproxySEXP);
    Rcpp::traits::input_parameter< List >::type obsproxy(obsproxySEXP);
    Rcpp::traits::input_parameter< List >::type sizeproxy(sizeproxySEXP);
    Rcpp::traits::input_parameter< List >::type sizebproxy(sizebproxySEXP);
    Rcpp::traits::input_parameter< List >::type sizecproxy(sizecproxySEXP);
    Rcpp::traits::input_parameter< List >::type repstproxy(repstproxySEXP);
    Rcpp::traits::input_parameter< List >::type fecproxy(fecproxySEXP);
    Rcpp::traits::input_parameter< List >::type jsurvproxy(jsurvproxySEXP);
    Rcpp::traits::input_parameter< List >::type jobsproxy(jobsproxySEXP);
    Rcpp::traits::input_parameter< List >::type jsizeproxy(jsizeproxySEXP);
    Rcpp::traits::input_parameter< List >::type jsizebproxy(jsizebproxySEXP);
    Rcpp::traits::input_parameter< List >::type jsizecproxy(jsizecproxySEXP);
    Rcpp::traits::input_parameter< List >::type jrepstproxy(jrepstproxySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f2_inda(f2_indaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f1_inda(f1_indaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f2_indb(f2_indbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f1_indb(f1_indbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f2_indc(f2_indcSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f1_indc(f1_indcSEXP);
    Rcpp::traits::input_parameter< StringVector >::type r2_inda(r2_indaSEXP);
    Rcpp::traits::input_parameter< StringVector >::type r1_inda(r1_indaSEXP);
    Rcpp::traits::input_parameter< StringVector >::type r2_indb(r2_indbSEXP);
    Rcpp::traits::input_parameter< StringVector >::type r1_indb(r1_indbSEXP);
    Rcpp::traits::input_parameter< StringVector >::type r2_indc(r2_indcSEXP);
    Rcpp::traits::input_parameter< StringVector >::type r1_indc(r1_indcSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dev_terms(dev_termsSEXP);
    Rcpp::traits::input_parameter< double >::type dens(densSEXP);
    Rcpp::traits::input_parameter< double >::type fecmod(fecmodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type svsigmas(svsigmasSEXP);
    Rcpp::traits::input_parameter< double >::type maxsize(maxsizeSEXP);
    Rcpp::traits::input_parameter< double >::type maxsizeb(maxsizebSEXP);
    Rcpp::traits::input_parameter< double >::type maxsizec(maxsizecSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type finalage(finalageSEXP);
    Rcpp::traits::input_parameter< int >::type sizedist(sizedistSEXP);
    Rcpp::traits::input_parameter< int >::type sizebdist(sizebdistSEXP);
    Rcpp::traits::input_parameter< int >::type sizecdist(sizecdistSEXP);
    Rcpp::traits::input_parameter< int >::type fecdist(fecdistSEXP);
    Rcpp::traits::input_parameter< bool >::type negfec(negfecSEXP);
    Rcpp::traits::input_parameter< double >::type exp_tol(exp_tolSEXP);
    Rcpp::traits::input_parameter< double >::type theta_tol(theta_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(jerzeibalowski(ppy, AllStages, stageframe, matrixformat, survproxy, obsproxy, sizeproxy, sizebproxy, sizecproxy, repstproxy, fecproxy, jsurvproxy, jobsproxy, jsizeproxy, jsizebproxy, jsizecproxy, jrepstproxy, f2_inda, f1_inda, f2_indb, f1_indb, f2_indc, f1_indc, r2_inda, r1_inda, r2_indb, r1_indb, r2_indc, r1_indc, dev_terms, dens, fecmod, svsigmas, maxsize, maxsizeb, maxsizec, finalage, sizedist, sizebdist, sizecdist, fecdist, negfec, exp_tol, theta_tol));
    return rcpp_result_gen;
END_RCPP
}
// stovokor
List stovokor(StringVector surv, StringVector obs, StringVector size, StringVector sizeb, StringVector sizec, StringVector repst, StringVector fec, StringVector vitalrates, bool historical, String suite, String approach, bool nojuvs, String age, StringVector indcova, StringVector indcovb, StringVector indcovc, String indiv, String patch, String year, bool pasrand, bool yasrand, bool iaasrand, bool ibasrand, bool icasrand, int fectime, bool juvsize, bool sizebused, bool sizecused, bool grouptest, String densitycol, bool densityused, bool indcovaused, bool indcovbused, bool indcovcused);
RcppExport SEXP _lefko3_stovokor(SEXP survSEXP, SEXP obsSEXP, SEXP sizeSEXP, SEXP sizebSEXP, SEXP sizecSEXP, SEXP repstSEXP, SEXP fecSEXP, SEXP vitalratesSEXP, SEXP historicalSEXP, SEXP suiteSEXP, SEXP approachSEXP, SEXP nojuvsSEXP, SEXP ageSEXP, SEXP indcovaSEXP, SEXP indcovbSEXP, SEXP indcovcSEXP, SEXP indivSEXP, SEXP patchSEXP, SEXP yearSEXP, SEXP pasrandSEXP, SEXP yasrandSEXP, SEXP iaasrandSEXP, SEXP ibasrandSEXP, SEXP icasrandSEXP, SEXP fectimeSEXP, SEXP juvsizeSEXP, SEXP sizebusedSEXP, SEXP sizecusedSEXP, SEXP grouptestSEXP, SEXP densitycolSEXP, SEXP densityusedSEXP, SEXP indcovausedSEXP, SEXP indcovbusedSEXP, SEXP indcovcusedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type surv(survSEXP);
    Rcpp::traits::input_parameter< StringVector >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< StringVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< StringVector >::type sizeb(sizebSEXP);
    Rcpp::traits::input_parameter< StringVector >::type sizec(sizecSEXP);
    Rcpp::traits::input_parameter< StringVector >::type repst(repstSEXP);
    Rcpp::traits::input_parameter< StringVector >::type fec(fecSEXP);
    Rcpp::traits::input_parameter< StringVector >::type vitalrates(vitalratesSEXP);
    Rcpp::traits::input_parameter< bool >::type historical(historicalSEXP);
    Rcpp::traits::input_parameter< String >::type suite(suiteSEXP);
    Rcpp::traits::input_parameter< String >::type approach(approachSEXP);
    Rcpp::traits::input_parameter< bool >::type nojuvs(nojuvsSEXP);
    Rcpp::traits::input_parameter< String >::type age(ageSEXP);
    Rcpp::traits::input_parameter< StringVector >::type indcova(indcovaSEXP);
    Rcpp::traits::input_parameter< StringVector >::type indcovb(indcovbSEXP);
    Rcpp::traits::input_parameter< StringVector >::type indcovc(indcovcSEXP);
    Rcpp::traits::input_parameter< String >::type indiv(indivSEXP);
    Rcpp::traits::input_parameter< String >::type patch(patchSEXP);
    Rcpp::traits::input_parameter< String >::type year(yearSEXP);
    Rcpp::traits::input_parameter< bool >::type pasrand(pasrandSEXP);
    Rcpp::traits::input_parameter< bool >::type yasrand(yasrandSEXP);
    Rcpp::traits::input_parameter< bool >::type iaasrand(iaasrandSEXP);
    Rcpp::traits::input_parameter< bool >::type ibasrand(ibasrandSEXP);
    Rcpp::traits::input_parameter< bool >::type icasrand(icasrandSEXP);
    Rcpp::traits::input_parameter< int >::type fectime(fectimeSEXP);
    Rcpp::traits::input_parameter< bool >::type juvsize(juvsizeSEXP);
    Rcpp::traits::input_parameter< bool >::type sizebused(sizebusedSEXP);
    Rcpp::traits::input_parameter< bool >::type sizecused(sizecusedSEXP);
    Rcpp::traits::input_parameter< bool >::type grouptest(grouptestSEXP);
    Rcpp::traits::input_parameter< String >::type densitycol(densitycolSEXP);
    Rcpp::traits::input_parameter< bool >::type densityused(densityusedSEXP);
    Rcpp::traits::input_parameter< bool >::type indcovaused(indcovausedSEXP);
    Rcpp::traits::input_parameter< bool >::type indcovbused(indcovbusedSEXP);
    Rcpp::traits::input_parameter< bool >::type indcovcused(indcovcusedSEXP);
    rcpp_result_gen = Rcpp::wrap(stovokor(surv, obs, size, sizeb, sizec, repst, fec, vitalrates, historical, suite, approach, nojuvs, age, indcova, indcovb, indcovc, indiv, patch, year, pasrand, yasrand, iaasrand, ibasrand, icasrand, fectime, juvsize, sizebused, sizecused, grouptest, densitycol, densityused, indcovaused, indcovbused, indcovcused));
    return rcpp_result_gen;
END_RCPP
}
// concat_dbl
NumericVector concat_dbl(NumericVector x, NumericVector y);
RcppExport SEXP _lefko3_concat_dbl(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(concat_dbl(x, y));
    return rcpp_result_gen;
END_RCPP
}
// concat_int
IntegerVector concat_int(IntegerVector x, IntegerVector y);
RcppExport SEXP _lefko3_concat_int(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(concat_int(x, y));
    return rcpp_result_gen;
END_RCPP
}
// concat_str
StringVector concat_str(StringVector x, StringVector y);
RcppExport SEXP _lefko3_concat_str(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< StringVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(concat_str(x, y));
    return rcpp_result_gen;
END_RCPP
}
// sf_create
Rcpp::List sf_create(NumericVector sizes, Nullable<StringVector> stagenames, Nullable<NumericVector> sizesb, Nullable<NumericVector> sizesc, Nullable<IntegerVector> repstatus, Nullable<IntegerVector> obsstatus, Nullable<IntegerVector> propstatus, Nullable<IntegerVector> matstatus, Nullable<IntegerVector> immstatus, Nullable<NumericVector> minage, Nullable<NumericVector> maxage, Nullable<IntegerVector> indataset, Nullable<NumericVector> binhalfwidth, Nullable<NumericVector> binhalfwidthb, Nullable<NumericVector> binhalfwidthc, Nullable<IntegerVector> group, Nullable<StringVector> comments, int roundsize, int roundsizeb, int roundsizec, int ipmbins, int ipmbinsb, int ipmbinsc);
RcppExport SEXP _lefko3_sf_create(SEXP sizesSEXP, SEXP stagenamesSEXP, SEXP sizesbSEXP, SEXP sizescSEXP, SEXP repstatusSEXP, SEXP obsstatusSEXP, SEXP propstatusSEXP, SEXP matstatusSEXP, SEXP immstatusSEXP, SEXP minageSEXP, SEXP maxageSEXP, SEXP indatasetSEXP, SEXP binhalfwidthSEXP, SEXP binhalfwidthbSEXP, SEXP binhalfwidthcSEXP, SEXP groupSEXP, SEXP commentsSEXP, SEXP roundsizeSEXP, SEXP roundsizebSEXP, SEXP roundsizecSEXP, SEXP ipmbinsSEXP, SEXP ipmbinsbSEXP, SEXP ipmbinscSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sizes(sizesSEXP);
    Rcpp::traits::input_parameter< Nullable<StringVector> >::type stagenames(stagenamesSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type sizesb(sizesbSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type sizesc(sizescSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type repstatus(repstatusSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type obsstatus(obsstatusSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type propstatus(propstatusSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type matstatus(matstatusSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type immstatus(immstatusSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type minage(minageSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type maxage(maxageSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type indataset(indatasetSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type binhalfwidth(binhalfwidthSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type binhalfwidthb(binhalfwidthbSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type binhalfwidthc(binhalfwidthcSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type group(groupSEXP);
    Rcpp::traits::input_parameter< Nullable<StringVector> >::type comments(commentsSEXP);
    Rcpp::traits::input_parameter< int >::type roundsize(roundsizeSEXP);
    Rcpp::traits::input_parameter< int >::type roundsizeb(roundsizebSEXP);
    Rcpp::traits::input_parameter< int >::type roundsizec(roundsizecSEXP);
    Rcpp::traits::input_parameter< int >::type ipmbins(ipmbinsSEXP);
    Rcpp::traits::input_parameter< int >::type ipmbinsb(ipmbinsbSEXP);
    Rcpp::traits::input_parameter< int >::type ipmbinsc(ipmbinscSEXP);
    rcpp_result_gen = Rcpp::wrap(sf_create(sizes, stagenames, sizesb, sizesc, repstatus, obsstatus, propstatus, matstatus, immstatus, minage, maxage, indataset, binhalfwidth, binhalfwidthb, binhalfwidthc, group, comments, roundsize, roundsizeb, roundsizec, ipmbins, ipmbinsb, ipmbinsc));
    return rcpp_result_gen;
END_RCPP
}
// sf_reassess
Rcpp::List sf_reassess(DataFrame stageframe, Nullable<DataFrame> supplement, Nullable<DataFrame> overwrite, Nullable<NumericMatrix> repmatrix, bool agemat, bool historical, int format);
RcppExport SEXP _lefko3_sf_reassess(SEXP stageframeSEXP, SEXP supplementSEXP, SEXP overwriteSEXP, SEXP repmatrixSEXP, SEXP agematSEXP, SEXP historicalSEXP, SEXP formatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type stageframe(stageframeSEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type supplement(supplementSEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type overwrite(overwriteSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type repmatrix(repmatrixSEXP);
    Rcpp::traits::input_parameter< bool >::type agemat(agematSEXP);
    Rcpp::traits::input_parameter< bool >::type historical(historicalSEXP);
    Rcpp::traits::input_parameter< int >::type format(formatSEXP);
    rcpp_result_gen = Rcpp::wrap(sf_reassess(stageframe, supplement, overwrite, repmatrix, agemat, historical, format));
    return rcpp_result_gen;
END_RCPP
}
// flagrantcrap
arma::vec flagrantcrap(arma::mat Xmat, arma::uvec allindices);
RcppExport SEXP _lefko3_flagrantcrap(SEXP XmatSEXP, SEXP allindicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type allindices(allindicesSEXP);
    rcpp_result_gen = Rcpp::wrap(flagrantcrap(Xmat, allindices));
    return rcpp_result_gen;
END_RCPP
}
// moreflagrantcrap
arma::vec moreflagrantcrap(arma::mat Xmat);
RcppExport SEXP _lefko3_moreflagrantcrap(SEXP XmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xmat(XmatSEXP);
    rcpp_result_gen = Rcpp::wrap(moreflagrantcrap(Xmat));
    return rcpp_result_gen;
END_RCPP
}
// spmat_log
arma::sp_mat spmat_log(arma::sp_mat coremat);
RcppExport SEXP _lefko3_spmat_log(SEXP corematSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type coremat(corematSEXP);
    rcpp_result_gen = Rcpp::wrap(spmat_log(coremat));
    return rcpp_result_gen;
END_RCPP
}
// turbogeodiesel
List turbogeodiesel(DataFrame loy, List Umats, List Fmats, DataFrame hstages, DataFrame agestages, DataFrame stages, bool patchmats, bool popmats);
RcppExport SEXP _lefko3_turbogeodiesel(SEXP loySEXP, SEXP UmatsSEXP, SEXP FmatsSEXP, SEXP hstagesSEXP, SEXP agestagesSEXP, SEXP stagesSEXP, SEXP patchmatsSEXP, SEXP popmatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type loy(loySEXP);
    Rcpp::traits::input_parameter< List >::type Umats(UmatsSEXP);
    Rcpp::traits::input_parameter< List >::type Fmats(FmatsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type hstages(hstagesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type agestages(agestagesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type stages(stagesSEXP);
    Rcpp::traits::input_parameter< bool >::type patchmats(patchmatsSEXP);
    Rcpp::traits::input_parameter< bool >::type popmats(popmatsSEXP);
    rcpp_result_gen = Rcpp::wrap(turbogeodiesel(loy, Umats, Fmats, hstages, agestages, stages, patchmats, popmats));
    return rcpp_result_gen;
END_RCPP
}
// geodiesel
List geodiesel(DataFrame loy, List Umats, List Fmats, DataFrame agestages, DataFrame stages, bool patchmats, bool popmats);
RcppExport SEXP _lefko3_geodiesel(SEXP loySEXP, SEXP UmatsSEXP, SEXP FmatsSEXP, SEXP agestagesSEXP, SEXP stagesSEXP, SEXP patchmatsSEXP, SEXP popmatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type loy(loySEXP);
    Rcpp::traits::input_parameter< List >::type Umats(UmatsSEXP);
    Rcpp::traits::input_parameter< List >::type Fmats(FmatsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type agestages(agestagesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type stages(stagesSEXP);
    Rcpp::traits::input_parameter< bool >::type patchmats(patchmatsSEXP);
    Rcpp::traits::input_parameter< bool >::type popmats(popmatsSEXP);
    rcpp_result_gen = Rcpp::wrap(geodiesel(loy, Umats, Fmats, agestages, stages, patchmats, popmats));
    return rcpp_result_gen;
END_RCPP
}
// decomp3
List decomp3(arma::mat Amat);
RcppExport SEXP _lefko3_decomp3(SEXP AmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    rcpp_result_gen = Rcpp::wrap(decomp3(Amat));
    return rcpp_result_gen;
END_RCPP
}
// decomp3sp
List decomp3sp(arma::mat Amat);
RcppExport SEXP _lefko3_decomp3sp(SEXP AmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    rcpp_result_gen = Rcpp::wrap(decomp3sp(Amat));
    return rcpp_result_gen;
END_RCPP
}
// decomp3sp_inp
List decomp3sp_inp(arma::sp_mat spAmat);
RcppExport SEXP _lefko3_decomp3sp_inp(SEXP spAmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type spAmat(spAmatSEXP);
    rcpp_result_gen = Rcpp::wrap(decomp3sp_inp(spAmat));
    return rcpp_result_gen;
END_RCPP
}
// lambda3matrix
double lambda3matrix(arma::mat Amat, bool sparse);
RcppExport SEXP _lefko3_lambda3matrix(SEXP AmatSEXP, SEXP sparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    Rcpp::traits::input_parameter< bool >::type sparse(sparseSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda3matrix(Amat, sparse));
    return rcpp_result_gen;
END_RCPP
}
// ss3matrix
arma::vec ss3matrix(arma::mat Amat, bool sparse);
RcppExport SEXP _lefko3_ss3matrix(SEXP AmatSEXP, SEXP sparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    Rcpp::traits::input_parameter< bool >::type sparse(sparseSEXP);
    rcpp_result_gen = Rcpp::wrap(ss3matrix(Amat, sparse));
    return rcpp_result_gen;
END_RCPP
}
// rv3matrix
arma::vec rv3matrix(arma::mat Amat, bool sparse);
RcppExport SEXP _lefko3_rv3matrix(SEXP AmatSEXP, SEXP sparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    Rcpp::traits::input_parameter< bool >::type sparse(sparseSEXP);
    rcpp_result_gen = Rcpp::wrap(rv3matrix(Amat, sparse));
    return rcpp_result_gen;
END_RCPP
}
// sens3matrix
arma::mat sens3matrix(arma::mat Amat, bool sparse);
RcppExport SEXP _lefko3_sens3matrix(SEXP AmatSEXP, SEXP sparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    Rcpp::traits::input_parameter< bool >::type sparse(sparseSEXP);
    rcpp_result_gen = Rcpp::wrap(sens3matrix(Amat, sparse));
    return rcpp_result_gen;
END_RCPP
}
// sens3sp_matrix
arma::sp_mat sens3sp_matrix(arma::sp_mat Aspmat, arma::sp_mat refmat);
RcppExport SEXP _lefko3_sens3sp_matrix(SEXP AspmatSEXP, SEXP refmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type Aspmat(AspmatSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type refmat(refmatSEXP);
    rcpp_result_gen = Rcpp::wrap(sens3sp_matrix(Aspmat, refmat));
    return rcpp_result_gen;
END_RCPP
}
// sens3hlefko
List sens3hlefko(arma::mat Amat, DataFrame ahstages, DataFrame hstages);
RcppExport SEXP _lefko3_sens3hlefko(SEXP AmatSEXP, SEXP ahstagesSEXP, SEXP hstagesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type ahstages(ahstagesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type hstages(hstagesSEXP);
    rcpp_result_gen = Rcpp::wrap(sens3hlefko(Amat, ahstages, hstages));
    return rcpp_result_gen;
END_RCPP
}
// elas3matrix
arma::mat elas3matrix(arma::mat Amat, bool sparse);
RcppExport SEXP _lefko3_elas3matrix(SEXP AmatSEXP, SEXP sparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    Rcpp::traits::input_parameter< bool >::type sparse(sparseSEXP);
    rcpp_result_gen = Rcpp::wrap(elas3matrix(Amat, sparse));
    return rcpp_result_gen;
END_RCPP
}
// elas3hlefko
List elas3hlefko(arma::mat Amat, DataFrame ahstages, DataFrame hstages);
RcppExport SEXP _lefko3_elas3hlefko(SEXP AmatSEXP, SEXP ahstagesSEXP, SEXP hstagesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type ahstages(ahstagesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type hstages(hstagesSEXP);
    rcpp_result_gen = Rcpp::wrap(elas3hlefko(Amat, ahstages, hstages));
    return rcpp_result_gen;
END_RCPP
}
// proj3
arma::mat proj3(arma::vec start_vec, List core_list, arma::uvec mat_order, bool standardize, bool growthonly, bool integeronly);
RcppExport SEXP _lefko3_proj3(SEXP start_vecSEXP, SEXP core_listSEXP, SEXP mat_orderSEXP, SEXP standardizeSEXP, SEXP growthonlySEXP, SEXP integeronlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type start_vec(start_vecSEXP);
    Rcpp::traits::input_parameter< List >::type core_list(core_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mat_order(mat_orderSEXP);
    Rcpp::traits::input_parameter< bool >::type standardize(standardizeSEXP);
    Rcpp::traits::input_parameter< bool >::type growthonly(growthonlySEXP);
    Rcpp::traits::input_parameter< bool >::type integeronly(integeronlySEXP);
    rcpp_result_gen = Rcpp::wrap(proj3(start_vec, core_list, mat_order, standardize, growthonly, integeronly));
    return rcpp_result_gen;
END_RCPP
}
// proj3sp
arma::mat proj3sp(arma::vec start_vec, List core_list, arma::uvec mat_order, bool standardize, bool growthonly, bool integeronly);
RcppExport SEXP _lefko3_proj3sp(SEXP start_vecSEXP, SEXP core_listSEXP, SEXP mat_orderSEXP, SEXP standardizeSEXP, SEXP growthonlySEXP, SEXP integeronlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type start_vec(start_vecSEXP);
    Rcpp::traits::input_parameter< List >::type core_list(core_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mat_order(mat_orderSEXP);
    Rcpp::traits::input_parameter< bool >::type standardize(standardizeSEXP);
    Rcpp::traits::input_parameter< bool >::type growthonly(growthonlySEXP);
    Rcpp::traits::input_parameter< bool >::type integeronly(integeronlySEXP);
    rcpp_result_gen = Rcpp::wrap(proj3sp(start_vec, core_list, mat_order, standardize, growthonly, integeronly));
    return rcpp_result_gen;
END_RCPP
}
// proj3dens
arma::mat proj3dens(arma::vec start_vec, List core_list, arma::uvec mat_order, bool growthonly, bool integeronly, int substoch, Rcpp::DataFrame dens_input, Rcpp::List dens_index);
RcppExport SEXP _lefko3_proj3dens(SEXP start_vecSEXP, SEXP core_listSEXP, SEXP mat_orderSEXP, SEXP growthonlySEXP, SEXP integeronlySEXP, SEXP substochSEXP, SEXP dens_inputSEXP, SEXP dens_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type start_vec(start_vecSEXP);
    Rcpp::traits::input_parameter< List >::type core_list(core_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mat_order(mat_orderSEXP);
    Rcpp::traits::input_parameter< bool >::type growthonly(growthonlySEXP);
    Rcpp::traits::input_parameter< bool >::type integeronly(integeronlySEXP);
    Rcpp::traits::input_parameter< int >::type substoch(substochSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dens_input(dens_inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type dens_index(dens_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(proj3dens(start_vec, core_list, mat_order, growthonly, integeronly, substoch, dens_input, dens_index));
    return rcpp_result_gen;
END_RCPP
}
// projection3
Rcpp::List projection3(List mpm, int nreps, int times, bool stochastic, bool standardize, bool growthonly, bool integeronly, int substoch, Nullable<NumericVector> start_vec, Nullable<DataFrame> start_frame, Nullable<NumericVector> tweights, Nullable<DataFrame> density);
RcppExport SEXP _lefko3_projection3(SEXP mpmSEXP, SEXP nrepsSEXP, SEXP timesSEXP, SEXP stochasticSEXP, SEXP standardizeSEXP, SEXP growthonlySEXP, SEXP integeronlySEXP, SEXP substochSEXP, SEXP start_vecSEXP, SEXP start_frameSEXP, SEXP tweightsSEXP, SEXP densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mpm(mpmSEXP);
    Rcpp::traits::input_parameter< int >::type nreps(nrepsSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    Rcpp::traits::input_parameter< bool >::type stochastic(stochasticSEXP);
    Rcpp::traits::input_parameter< bool >::type standardize(standardizeSEXP);
    Rcpp::traits::input_parameter< bool >::type growthonly(growthonlySEXP);
    Rcpp::traits::input_parameter< bool >::type integeronly(integeronlySEXP);
    Rcpp::traits::input_parameter< int >::type substoch(substochSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type start_vec(start_vecSEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type start_frame(start_frameSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type tweights(tweightsSEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type density(densitySEXP);
    rcpp_result_gen = Rcpp::wrap(projection3(mpm, nreps, times, stochastic, standardize, growthonly, integeronly, substoch, start_vec, start_frame, tweights, density));
    return rcpp_result_gen;
END_RCPP
}
// slambda3
DataFrame slambda3(List mpm, int times, bool dense_only, Nullable<NumericVector> tweights);
RcppExport SEXP _lefko3_slambda3(SEXP mpmSEXP, SEXP timesSEXP, SEXP dense_onlySEXP, SEXP tweightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mpm(mpmSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    Rcpp::traits::input_parameter< bool >::type dense_only(dense_onlySEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type tweights(tweightsSEXP);
    rcpp_result_gen = Rcpp::wrap(slambda3(mpm, times, dense_only, tweights));
    return rcpp_result_gen;
END_RCPP
}
// stoch_senselas
Rcpp::List stoch_senselas(List mpm, int times, int style, Nullable<NumericVector> tweights);
RcppExport SEXP _lefko3_stoch_senselas(SEXP mpmSEXP, SEXP timesSEXP, SEXP styleSEXP, SEXP tweightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mpm(mpmSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    Rcpp::traits::input_parameter< int >::type style(styleSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type tweights(tweightsSEXP);
    rcpp_result_gen = Rcpp::wrap(stoch_senselas(mpm, times, style, tweights));
    return rcpp_result_gen;
END_RCPP
}
// bambi3
DataFrame bambi3(DataFrame stages, DataFrame hstages);
RcppExport SEXP _lefko3_bambi3(SEXP stagesSEXP, SEXP hstagesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type stages(stagesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type hstages(hstagesSEXP);
    rcpp_result_gen = Rcpp::wrap(bambi3(stages, hstages));
    return rcpp_result_gen;
END_RCPP
}
// bambi2
DataFrame bambi2(DataFrame stages);
RcppExport SEXP _lefko3_bambi2(SEXP stagesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type stages(stagesSEXP);
    rcpp_result_gen = Rcpp::wrap(bambi2(stages));
    return rcpp_result_gen;
END_RCPP
}
// demolition3
List demolition3(arma::mat e_amat, DataFrame bambesque, Nullable<Rcpp::NumericVector> amat_, Nullable<Rcpp::NumericVector> fmat_);
RcppExport SEXP _lefko3_demolition3(SEXP e_amatSEXP, SEXP bambesqueSEXP, SEXP amat_SEXP, SEXP fmat_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type e_amat(e_amatSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type bambesque(bambesqueSEXP);
    Rcpp::traits::input_parameter< Nullable<Rcpp::NumericVector> >::type amat_(amat_SEXP);
    Rcpp::traits::input_parameter< Nullable<Rcpp::NumericVector> >::type fmat_(fmat_SEXP);
    rcpp_result_gen = Rcpp::wrap(demolition3(e_amat, bambesque, amat_, fmat_));
    return rcpp_result_gen;
END_RCPP
}
// ltre3matrix
arma::cube ltre3matrix(List Amats, Rcpp::IntegerVector refnum, Nullable<Rcpp::List> refmats_, bool mean, bool sparse);
RcppExport SEXP _lefko3_ltre3matrix(SEXP AmatsSEXP, SEXP refnumSEXP, SEXP refmats_SEXP, SEXP meanSEXP, SEXP sparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Amats(AmatsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type refnum(refnumSEXP);
    Rcpp::traits::input_parameter< Nullable<Rcpp::List> >::type refmats_(refmats_SEXP);
    Rcpp::traits::input_parameter< bool >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< bool >::type sparse(sparseSEXP);
    rcpp_result_gen = Rcpp::wrap(ltre3matrix(Amats, refnum, refmats_, mean, sparse));
    return rcpp_result_gen;
END_RCPP
}
// sltre3matrix
Rcpp::List sltre3matrix(List Amats, DataFrame loy, Rcpp::IntegerVector refnum, Nullable<Rcpp::List> refmats_, Nullable<arma::vec> tweights_, int steps, int burnin, bool sparse);
RcppExport SEXP _lefko3_sltre3matrix(SEXP AmatsSEXP, SEXP loySEXP, SEXP refnumSEXP, SEXP refmats_SEXP, SEXP tweights_SEXP, SEXP stepsSEXP, SEXP burninSEXP, SEXP sparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Amats(AmatsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type loy(loySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type refnum(refnumSEXP);
    Rcpp::traits::input_parameter< Nullable<Rcpp::List> >::type refmats_(refmats_SEXP);
    Rcpp::traits::input_parameter< Nullable<arma::vec> >::type tweights_(tweights_SEXP);
    Rcpp::traits::input_parameter< int >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< bool >::type sparse(sparseSEXP);
    rcpp_result_gen = Rcpp::wrap(sltre3matrix(Amats, loy, refnum, refmats_, tweights_, steps, burnin, sparse));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lefko3_ovreplace", (DL_FUNC) &_lefko3_ovreplace, 7},
    {"_lefko3_pfj", (DL_FUNC) &_lefko3_pfj, 40},
    {"_lefko3_jpf", (DL_FUNC) &_lefko3_jpf, 52},
    {"_lefko3_theoldpizzle", (DL_FUNC) &_lefko3_theoldpizzle, 7},
    {"_lefko3_density3", (DL_FUNC) &_lefko3_density3, 5},
    {"_lefko3_hoffmannofstuttgart", (DL_FUNC) &_lefko3_hoffmannofstuttgart, 4},
    {"_lefko3_cond_hmpm", (DL_FUNC) &_lefko3_cond_hmpm, 3},
    {"_lefko3_specialpatrolgroup", (DL_FUNC) &_lefko3_specialpatrolgroup, 6},
    {"_lefko3_normalpatrolgroup", (DL_FUNC) &_lefko3_normalpatrolgroup, 4},
    {"_lefko3_revelations", (DL_FUNC) &_lefko3_revelations, 14},
    {"_lefko3_rimeotam", (DL_FUNC) &_lefko3_rimeotam, 18},
    {"_lefko3_foi_counter", (DL_FUNC) &_lefko3_foi_counter, 2},
    {"_lefko3_flightoficarus", (DL_FUNC) &_lefko3_flightoficarus, 1},
    {"_lefko3_bootson", (DL_FUNC) &_lefko3_bootson, 1},
    {"_lefko3_zero_flightoficarus", (DL_FUNC) &_lefko3_zero_flightoficarus, 1},
    {"_lefko3_zero_bootson", (DL_FUNC) &_lefko3_zero_bootson, 1},
    {"_lefko3_foi_index", (DL_FUNC) &_lefko3_foi_index, 13},
    {"_lefko3_jerzeibalowski", (DL_FUNC) &_lefko3_jerzeibalowski, 44},
    {"_lefko3_stovokor", (DL_FUNC) &_lefko3_stovokor, 34},
    {"_lefko3_concat_dbl", (DL_FUNC) &_lefko3_concat_dbl, 2},
    {"_lefko3_concat_int", (DL_FUNC) &_lefko3_concat_int, 2},
    {"_lefko3_concat_str", (DL_FUNC) &_lefko3_concat_str, 2},
    {"_lefko3_sf_create", (DL_FUNC) &_lefko3_sf_create, 23},
    {"_lefko3_sf_reassess", (DL_FUNC) &_lefko3_sf_reassess, 7},
    {"_lefko3_flagrantcrap", (DL_FUNC) &_lefko3_flagrantcrap, 2},
    {"_lefko3_moreflagrantcrap", (DL_FUNC) &_lefko3_moreflagrantcrap, 1},
    {"_lefko3_spmat_log", (DL_FUNC) &_lefko3_spmat_log, 1},
    {"_lefko3_turbogeodiesel", (DL_FUNC) &_lefko3_turbogeodiesel, 8},
    {"_lefko3_geodiesel", (DL_FUNC) &_lefko3_geodiesel, 7},
    {"_lefko3_decomp3", (DL_FUNC) &_lefko3_decomp3, 1},
    {"_lefko3_decomp3sp", (DL_FUNC) &_lefko3_decomp3sp, 1},
    {"_lefko3_decomp3sp_inp", (DL_FUNC) &_lefko3_decomp3sp_inp, 1},
    {"_lefko3_lambda3matrix", (DL_FUNC) &_lefko3_lambda3matrix, 2},
    {"_lefko3_ss3matrix", (DL_FUNC) &_lefko3_ss3matrix, 2},
    {"_lefko3_rv3matrix", (DL_FUNC) &_lefko3_rv3matrix, 2},
    {"_lefko3_sens3matrix", (DL_FUNC) &_lefko3_sens3matrix, 2},
    {"_lefko3_sens3sp_matrix", (DL_FUNC) &_lefko3_sens3sp_matrix, 2},
    {"_lefko3_sens3hlefko", (DL_FUNC) &_lefko3_sens3hlefko, 3},
    {"_lefko3_elas3matrix", (DL_FUNC) &_lefko3_elas3matrix, 2},
    {"_lefko3_elas3hlefko", (DL_FUNC) &_lefko3_elas3hlefko, 3},
    {"_lefko3_proj3", (DL_FUNC) &_lefko3_proj3, 6},
    {"_lefko3_proj3sp", (DL_FUNC) &_lefko3_proj3sp, 6},
    {"_lefko3_proj3dens", (DL_FUNC) &_lefko3_proj3dens, 8},
    {"_lefko3_projection3", (DL_FUNC) &_lefko3_projection3, 12},
    {"_lefko3_slambda3", (DL_FUNC) &_lefko3_slambda3, 4},
    {"_lefko3_stoch_senselas", (DL_FUNC) &_lefko3_stoch_senselas, 4},
    {"_lefko3_bambi3", (DL_FUNC) &_lefko3_bambi3, 2},
    {"_lefko3_bambi2", (DL_FUNC) &_lefko3_bambi2, 1},
    {"_lefko3_demolition3", (DL_FUNC) &_lefko3_demolition3, 4},
    {"_lefko3_ltre3matrix", (DL_FUNC) &_lefko3_ltre3matrix, 5},
    {"_lefko3_sltre3matrix", (DL_FUNC) &_lefko3_sltre3matrix, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_lefko3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
